# Generated by Django 4.1 on 2022-08-29 06:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0005_notes_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="notes",
            name="archive",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notes",
            name="sharedwith",
            field=models.ManyToManyField(
                related_name="shared", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="notes",
            name="title",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="notes",
            name="date_created",
            field=models.DateField(default="2022-08-29"),
        ),
    ]
