# Generated by Django 4.1 on 2022-08-29 11:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0006_notes_archive_notes_sharedwith_notes_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notes",
            name="sharedwith",
            field=models.ManyToManyField(
                blank=True, related_name="shared", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
